[package]
name = "rent-commodity-exchange"
version = "0.1.0"
edition = "2024"

[dependencies]
microlp = "0.2.9"
rand = { version = "0.9.0", optional = true }

[features]
default = ["rand"]
rand = ["dep:rand"]
