[package]
name = "rent-commodity-exchange"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.9.0", optional = true }
russcip = { version = "0.6.1", features = ["bundled"] }

[features]
default = ["rand"]
rand = ["dep:rand"]
